version: '3'

services:
  postgree:
    container_name: dbpostgres
    image: postgres:${IMAGE_TEG}
    ports: 
      - "5432:5432"
    networks: 
      - postgree_network
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  pgAdmin:
    container_name: dbAdminPostgres
    image: dpage/pgadmin4
    ports: 
      - "8080:80"
    networks: 
      - postgree_network
    environment: 
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}

networks: 
  postgree_network: 
    driver: bridge