services:
  aws-local:
    container_name: "aws-local"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510-4559:4510-4559"
    environment:
      - PERSISTENCE=1
      - DEBUG=0
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
#      - "./localstack/localstack-pods:/pods"
#      - "./localstack/scripts/boot.sh:/etc/localstack/init/boot.d/boot.sh"
#      - "./localstack/scripts/init.sh:/etc/localstack/init/ready.d/init.sh"
#      - "./localstack/scripts/shutdown.sh:/etc/localstack/init/shutdown.d/shutdown.sh"
      - "./localstack/data:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"